[env]
TERM = "xterm-256color"
[window]
opacity = 0.7

[font]
size = 12.7 # this is usually 11 but it looks better 12.7
[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"
[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"
[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
	#"~/.config/alacritty/catppuccin-frappe.toml"
	"~/.config/alacritty/nord.toml"
]
